### ISSUE TITLE
Software from JetBrains should not allow committing the `.idea` folder by default

### ISSUE THREAD

**Issue by InfernumPegasus** [InfernumPegasus/BattleCity#2]
Also, what's your ID? Software from JetBrains should not allow committing the `.idea` folder by default

_Originally posted by @uselessgoddess in https://github.com/InfernumPegasus/BattleCity/pull/1#pullrequestreview-1244036146_

**Comment by uselessgoddess** [comment]
It's my typo: `ID` -> `IDE` 😥
